// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz9bzCzALaBZJS1fCfaVpzVKe4zk0Ol5o',
    appId: '1:850193877373:web:a771a5df62264684dbe414',
    messagingSenderId: '850193877373',
    projectId: 'embark-mobile-fcfc7',
    authDomain: 'embark-mobile-fcfc7.firebaseapp.com',
    databaseURL: 'https://embark-mobile-fcfc7-default-rtdb.firebaseio.com',
    storageBucket: 'embark-mobile-fcfc7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvzHkLBIkPUercAF3YUSUuol9gdwyHaLs',
    appId: '1:850193877373:android:dfeb2cb41cfba3dfdbe414',
    messagingSenderId: '850193877373',
    projectId: 'embark-mobile-fcfc7',
    databaseURL: 'https://embark-mobile-fcfc7-default-rtdb.firebaseio.com',
    storageBucket: 'embark-mobile-fcfc7.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCz9bzCzALaBZJS1fCfaVpzVKe4zk0Ol5o',
    appId: '1:850193877373:web:2292759f209bf35adbe414',
    messagingSenderId: '850193877373',
    projectId: 'embark-mobile-fcfc7',
    authDomain: 'embark-mobile-fcfc7.firebaseapp.com',
    databaseURL: 'https://embark-mobile-fcfc7-default-rtdb.firebaseio.com',
    storageBucket: 'embark-mobile-fcfc7.firebasestorage.app',
  );

}